version: "3.9"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgrespass
    ports:
      - 5432:5432
  redpanda:
    image: vectorized/redpanda:latest
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://0.0.0.0:9092
    ports:
      - 9092:9092
      - 29092:29092
  kafka-ui:
    image: obsidiandynamics/kafdrop
    ports:
      - 8080:9000
    environment:
      KAFKA_BROKERCONNECT: redpanda:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
  redis:
    image: redis:6.2.3-alpine
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    depends_on:
      - redpanda
    ports:
      - "9000:9000"
    entrypoint: >
      /bin/sh -c "
      curl https://raw.githubusercontent.com/hetacode/tiny-battleship/master/wait-for-it.sh -o wait-for-it.sh;
      chmod +x wait-for-it.sh;
      ./wait-for-it.sh redpanda:29092 -- /usr/bin/docker-entrypoint.sh minio server /export;
      "
  mc:
    image: minio/mc
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      mc config host add minio http://minio:9000 minioadmin minioadmin;
      mc admin config get minio notify_kafka;
      mc admin config set minio notify_kafka:1 tls_skip_verify="off" queue_dir="" queue_limit="0" sasl="off" sasl_password="" sasl_username="" tls_client_auth="0" tls="off" client_tls_cert="" client_tls_key="" brokers="redpanda:29092" topic="minio-events-inputs";
      mc admin config set minio notify_kafka:2 tls_skip_verify="off" queue_dir="" queue_limit="0" sasl="off" sasl_password="" sasl_username="" tls_client_auth="0" tls="off" client_tls_cert="" client_tls_key="" brokers="redpanda:29092" topic="minio-events-outputs";
      mc admin service restart minio;
      mc mb minio/inputs;
      mc mb minio/outputs;
      mc mb minio/templates;
      mc event add minio/inputs arn:minio:sqs::1:kafka --suffix .yaml;
      mc event add minio/outputs arn:minio:sqs::2:kafka --suffix .*;
      mc event list minio/inputs;
      mc event list minio/outputs;
      "
    depends_on:
      - minio
      - redpanda

  repository-processor-func:
    build:
      context: src/RepositoryProcessorFunc
      dockerfile: Dockerfile
    image: repository-processor-func
    ports:
      - 7000:80
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
      - CODE_REPOSITORY=https://github.com/hetacode/heta-template-app.git
  template-processor-func:
    build:
      context: src/TemplateProcessorFunc
      dockerfile: Dockerfile
    image: template-processor-func
    ports:
      - 7001:80
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
  input-processor-func:
    build:
      context: .
      dockerfile: src/InputProcessorFunc/Dockerfile
    image: input-processor-func
    environment:
      - KAFKA_BROKERS=redpanda:29092
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
  profile-page-generator-func:
    build:
      context: .
      dockerfile: src/ProfilePageGeneratorFunc/Dockerfile
    image: profile-page-generator-func
    environment:
      - KAFKA_BROKERS=redpanda:29092
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
