{{ range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $service.app }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
        
{{ println "---" }}          
{{- end }}