apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: minio-app
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/address-pool: metal-lb-ip-pool
spec:
  type: LoadBalancer
  selector:
    app: minio-app
  ports:
    - name: storage
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: web-ui 
      port: 9001
      targetPort: 9001
      protocol: TCP
