apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-cluster-0
  ports:
    - protocol: TCP
      name: kafka-api
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: panda-proxy-api
      port: 8082
      targetPort: 8082