apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda-cluster
  ports:
    - protocol: TCP
      name: kafka-api
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: panda-proxy-api
      port: 8082
      targetPort: 8082