name: Build and push docker images

on:
  workflow_dispatch:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_REGISTRY: $REGISTRY/$IMAGE_NAME
  DOCKER_TAG: ${{ github.run_number }}

jobs:
  build_and_push:
    name: Build and push to the Github Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace tokens inside build version of docker-compose
        uses: vafinvr/template-env-action@v2.0.1
        with:
          filename: docker-compose.build.yaml
          
      - name: Build images
        run: |
          docker-compose -f docker-compose.build.yaml build
      
      - name: Push images to the Github Registry
        run: |
          docker-compose -f docker-compose.build.yaml push